layouts/_default/baseof.html
static/icons/icon.css

icons locally

---

layouts/_default/baseof.html

Reverts portworx/pxdocs-tooling#4

Revert "Ga tracking"

---

layouts/partials/topbar.html

- Updated link in header to be https

fixed http link

---

static/css/styles.css

- Code highlighting fixed for YAML

code highlight for blocks fixed

---

layouts/_default/baseof.html

- Utilized the Permalink to make link checking dynamic to environment.

fix for link checker

---

layouts/partials/prevnext.html
static/css/styles.css

- Added link for forums in prev/next section

forum link in prevnext

---

layouts/shortcodes/direct-download.html

add direct-download shortcode

---

deploy/nginx/nginx.conf

add rewrite rules for kubemotion

add rewrite rules for kubemotion

---

deploy/nginx/nginx.conf

rename kubemotion to datamigration for non8s schedulers

rename kubemotion to datamigration for nonk8s schedulers

---

layouts/shortcodes/interactivelist.html

add missing interactive tutorials

add missing interactive tutorials

---

deploy/nginx/nginx.conf

redirect out to Pxcentral tutorials

---

layouts/shortcodes/youtube.html

Here is the original, which does not have time. https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/shortcodes/youtube.html

updates youtube shortcode to allow start time

---

deploy/algolia/package-lock.json
deploy/algolia/package.json

Fix security vulnerabilities

---

deploy/manifests/pxbackup/deployment.yaml
deploy/manifests/pxbackup/pxbackup-ingress.yaml
deploy/manifests/pxbackup/service-template.yaml

PX-Backup: Update namespace

---

layouts/shortcodes/currentVersion.html

PD-460 Update Portworx version based on the doc version

PD-460 Update Portworx version based on the doc version

---

layouts/shortcodes/currentVersion.html

currentVersion should default to a safe value

currentVersion should default to a safe value

---

layouts/shortcodes/currentVersion.html

Trim whitespaces

---

layouts/shortcodes/widelink.html

PD-283 Remove or replace the play icon in the wide link divs

---

layouts/partials/prevnext.html

Remove newlines

---

layouts/partials/prevnext.html

comment out edit on github

---

layouts/shortcodes/open-in-new-tab.html

PD-225 open-in-new-tab-shortcode

---

layouts/partials/topbar.html

add free trial and login links to docs header

PD-470: add free trial and login links to docs header

---

layouts/_default/list.algolia.json

Include product URL in Algolia index

PD-549: Include the product URL in Algolia

---

layouts/_default/baseof.html
static/css/styles.css
static/js/docs.js

Refactor federated search

---

static/css/styles.css

top nav cta style changes to match px.com

style.css changes

---

static/css/styles.css

Make sidebar stick to the header

Make sidebar stick to the header

---

layouts/shortcodes/homelist.html

PD-238: Change release notes page to tiles

---

layouts/shortcodes/homelist.html
static/css/styles.css

PD-600: Change series tiles to not use h3s

PD-600: Change series tiles to not use h3s

---

static/swagger-ui/index.html
static/swagger-ui/o2c.html

Swagger doctype

---

layouts/_default/baseof.html
static/js/docs.js

productName  -> index-name

---

build/Dockerfile
build/Makefile
build/before_install.sh
build/build.sh
build/export-product-url.sh
build/products.yaml

PD-671: Unify our build tools

---

deploy/manifests/deployment.yaml
deploy/manifests/ingress-default.yaml

Update specs for Kubernetes 1.6

Update specs for Kubernetes 1.6

---

deploy/manifests/pxbackup/deployment.yaml
deploy/manifests/pxbackup/pxbackup-ingress.yaml

PX-Backup: Update specs for Kubernetes 1.6

---

layouts/shortcodes/currentVersion.html

PD-538 Improve the currentVersion shortcode

---

build/Makefile
layouts/shortcodes/currentVersion.html

PD- 538: Improve the currentVersion shortcode

PD- 538: Improve the currentVersion shortcode

---

build/before_install.sh
build/build.sh
build/products.yaml

PD-748: Upgrade yq and remove duplicated code

PD-748: Upgrade yq and remove duplicated code

---

build/products.yaml

PX-Enterprise 2.7

---

build/before_install.sh

PD-821 add docker login to preinstall script

---

build/before_install.sh

Pd 821 improve dockerhub pull limit

---

build/Dockerfile

Add Asciidoctor support to Hugo

---

build/Makefile
build/build.sh
build/products.yaml
deploy/manifests/pxcentral/deployment.yaml
deploy/manifests/pxcentral/pxcentral-ingress.yaml
deploy/manifests/pxcentral/service-template.yaml
layouts/partials/menu.html

PX-Central

---

build/Dockerfile

PD-843 Bump Hugo version to 0.88.1

---

static/css/styles.css
static/js/docs.js

This JQuery needs to go. Everything about the docs.js file is bad news.

Bandage codeblocks

---

layouts/_default/baseof.html

PD-960 Add LinkedIn tag

---

static/css/styles.css

Add CSS for Asciidoc

---

layouts/partials/footer.html
layouts/partials/topbar.html
static/js/docs.js

PD-1135 requested tooling changes/fixes

---

build/build.sh
build/products.yaml

PD-1115 Add more PDS tooling

---

deploy/manifests/pds/deployment.yaml
deploy/manifests/pds/pxcentral-ingress.yaml
deploy/manifests/pds/service-template.yaml

PD-1115 pt. 3 update manifests

---

deploy/manifests/pds/pds-ingress.yaml

PDS fix ingress title and add missing redirect file

---

build/products.yaml

Readd PDS to products yaml

---

build/Makefile
build/build.sh
build/products.yaml
deploy/manifests/saasbackup/deployment.yaml
deploy/manifests/saasbackup/saasbackup-ingress.yaml
deploy/manifests/saasbackup/service-template.yaml
deploy/nginx/Dockerfile

Add tooling support for Backup SaaS

---

deploy/nginx/px-enterprise-redirects.conf

fix redirect loop

---

layouts/shortcodes/automateTable.html

add a table automation shortcode

---

layouts/partials/topbar.html
static/css/styles.css

Fix list margins

---

layouts/shortcodes/variable.html

Create a new variable shortcode that uses arguments

---

build/before_install.sh

experimental: Pull data from other repos

---

build/before_install.sh

Pull data other repos

---

build/before_install.sh

add curl to pull version

---

static/css/styles.css
static/js/docs.js

I don't think these bits are used by anything else. The main page of the site builds fine without this stuff. Anything else in particular I should check?

PD-1395 get rid of drop down menu css and js

---

layouts/shortcodes/highlight.html
static/css/styles.css

textbox highlighting

---

layouts/shortcodes/highlight.html

fix highlighting shortcode for "<>" brackets

---

layouts/_default/cli-reference.html

pxctl CLI reference

---

deploy/nginx/px-enterprise-redirects.conf

PD-1545 redirect from deleted FAQ to forum

---

deploy/manifests/ingress-default.yaml
deploy/manifests/pds/pds-ingress.yaml
deploy/manifests/pds/service-template.yaml
deploy/manifests/pxbackup/service-template.yaml
deploy/manifests/pxcentral/pxcentral-ingress-2-4.yaml
deploy/manifests/pxcentral/pxcentral-ingress-2-5.yaml
deploy/manifests/pxcentral/pxcentral-ingress.yaml
deploy/manifests/pxcentral/service-template.yaml
deploy/manifests/saasbackup/saasbackup-ingress.yaml
deploy/manifests/saasbackup/service-template.yaml
deploy/manifests/service-template.yaml

update specs with new format needed for k8s 1.23

---

deploy/manifests/pds/pds-ingress.yaml
deploy/manifests/pds/service-template.yaml
deploy/manifests/pxbackup/pxbackup-ingress-2-4.yaml
deploy/manifests/pxbackup/pxbackup-ingress-2-5.yaml
deploy/manifests/pxbackup/service-template.yaml
deploy/manifests/pxcentral/pxcentral-ingress-2-4.yaml
deploy/manifests/pxcentral/pxcentral-ingress-2-5.yaml
deploy/manifests/pxcentral/pxcentral-ingress.yaml
deploy/manifests/pxcentral/service-template.yaml
deploy/manifests/saasbackup/saasbackup-ingress.yaml
deploy/manifests/saasbackup/service-template.yaml

Gke k8s 1-23 fix 2

---

layouts/partials/alert.html
static/css/styles.css

This PR add functionality to alert bar, to have multiple alert bar based on the alert.yaml file under data folder and also changes the text size and text format, from bold to normal. Lastly, allow to embed url under the alert banner.
Closes #

add alert css and update partial html

---

build/build.sh

Updated algolia key
